version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: ./trainerhub
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./trainerhub:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    depends_on:
      - db
volumes:
  postgres_data:
